# Repository Statistics Configuration
repositories:
  # Existing repositories
  - name: "housing-hub-saas"
    display_name: "InmoIA Frontend"
    branch: "develop"
    artifact_name: "repo1-stats"
    organization: "guillermo-affiliaction"
    token_type: "private"
  - name: "backend-housing-hub-saas"
    display_name: "TypeScript Backend"
    branch: "develop"
    artifact_name: "repo2-stats"
    organization: "guillermo-affiliaction"
    token_type: "private"
  - name: "IAbackend-inmoIA"
    display_name: "Python AI MCP Backend"
    branch: "develop"
    artifact_name: "repo3-stats"
    organization: "guillermo-affiliaction"
    token_type: "private"

  # Your personal repositories
  - name: "FacturaIA"
    display_name: "FacturaIA"
    branch: "develop"
    artifact_name: "repo4-stats"
    organization: "GuillermoAstorgaCalvo"
    token_type: "personal"
  - name: "restaurant-app"
    display_name: "Restaurant App"
    branch: "develop"
    artifact_name: "repo5-stats"
    organization: "GuillermoAstorgaCalvo"
    token_type: "personal"

# GitHub organization/user settings
github:
  organization: "guillermo-affiliaction" # Keep this for existing repos
  base_url: "https://github.com"
  username: "GuillermoAstorgaCalvo"

  # GitHub Token Configuration
  # These tokens are used for API access to repositories
  # Set these as environment variables or GitHub Actions secrets
  tokens:
    # For private repositories (guillermo-affiliaction organization)
    # Required permissions: repo:read, contents:read, metadata:read
    private_token_env: "PRIVATE_REPOS_TOKEN"

    # For personal repositories (GuillermoAstorgaCalvo user)
    # Required permissions: repo:read, contents:read, metadata:read
    personal_token_env: "PERSONAL_REPOS_TOKEN"

    # Token setup instructions:
    # 1. Create Personal Access Token at: https://github.com/settings/tokens
    # 2. For private repos: Use fine-grained token with repo access
    # 3. For personal repos: Use classic token with 'repo' scope
    # 4. Set environment variables:
    #    export PRIVATE_REPOS_TOKEN="ghp_your_private_token_here"
    #    export PERSONAL_REPOS_TOKEN="ghp_your_personal_token_here"

# External services and URLs
external_services:
  # Social media and contact
  linkedin: "https://linkedin.com/in/guillermoastorgacalvo"
  email: "mailto:guillermo.astorga.calvo@gmail.com"
  portfolio: "https://guillermoastorgacalvo.dev"

  # Badge services
  shields_io: "https://img.shields.io/badge"
  skill_icons: "https://skillicons.dev/icons"
  readme_typing: "https://readme-typing-svg.herokuapp.com"

  # GitHub stats services
  github_stats: "https://github-readme-stats.vercel.app/api"
  github_streak: "https://streak-stats.demolab.com"
  github_activity: "https://github-readme-activity-graph.vercel.app/graph"
  profile_views: "https://komarev.com/ghpvc"

  # Project URLs
  project_urls:
    inmoia_frontend: "https://github.com/guillermo-affiliaction/housing-hub-saas"
    typescript_backend: "https://github.com/guillermo-affiliaction/backend-housing-hub-saas"
    python_ai_backend: "https://github.com/guillermo-affiliaction/IAbackend-inmoIA"
    facturaia: "https://github.com/GuillermoAstorgaCalvo/FacturaIA"
    restaurant_app: "https://restauranteguillermoastorga.up.railway.app/"

# Author pattern matching
author_patterns:
  guillermo:
    - "guillermo.*affiliaction"
    - "Guillermo.*Affiliaction"
    - "GuillermoAstorgaCalvo"
    - "guillermoastorgacalvo"
    - "Guillermo Astorga"
    - "Guillermo Astorga Calvo"
    - "guillermo.*astorga"
    - "Guillermo.*Astorga"
  bots:
    - ".*\\[bot\\]$"
    - "gpt-engineer-app.*"

# Processing settings
processing:
  timeout_seconds: 60 # Reduced timeout for faster execution
  git_fame_format: "json"

# Report settings
report:
  title: "📊 Unified Code Statistics"
  sections:
    - "Global Summary"
    - "Contributions by Repository and Author"
  date_format: "%B %d, %Y at %H:%M UTC"

# Artifact settings
artifacts:
  retention_days: 1
  stats_filename: "repo_stats.json"

# Analytics and historical tracking
analytics:
  track_history: true
  retention_days: 90
  trend_analysis: true
  language_tracking: true

  # Growth tracking settings
  growth_tracking:
    enabled: true
    metrics:
      - "total_loc"
      - "total_commits"
      - "total_files"
      - "guillermo_loc"
      - "guillermo_commits"
      - "guillermo_files"

  # Velocity metrics (weekly/monthly rates)
  velocity_metrics:
    enabled: true
    periods:
      - "weekly"
      - "monthly"
      - "quarterly"

  # Language usage tracking
  language_usage:
    enabled: true
    track_top_languages: 10
    show_percentage: true
    include_unknown: false

# README generation settings
readme:
  # Badge colors and styling
  badge_colors:
    primary: "58A6FF"
    secondary: "4ECDC4"
    accent: "FF6B6B"
    purple: "9C27B0"
    dark: "0D1117"
    light: "8B949E"

  # Typing animation settings
  typing_animation:
    font: "Fira+Code"
    weight: "500"
    size: "28"
    pause: "1000"
    color: "58A6FF"
    center: "true"
    vCenter: "true"
    width: "600"
    height: "100"
    lines: "Full-Stack+Developer;AI+Enthusiast;Problem+Solver;Code+Craftsman"

  # Profile information
  profile:
    name: "Guillermo"
    title: "Full-Stack Developer"
    subtitle: "AI Enthusiast | Problem Solver | Code Craftsman"
    description: "I build things. Sometimes they work, sometimes they don't, but I always learn something along the way."

  # Contact information
  contact:
    linkedin: "guillermoastorgacalvo"
    email: "guillermo.astorga.calvo@gmail.com"
    portfolio: "guillermoastorgacalvo.dev"
