# Repository Statistics Configuration
repositories:
  - name: "housing-hub-saas"
    display_name: "InmoIA Frontend"
    branch: "develop"
    artifact_name: "repo1-stats"
  - name: "backend-housing-hub-saas"
    display_name: "TypeScript Backend"
    branch: "develop"
    artifact_name: "repo2-stats"
  - name: "IAbackend-inmoIA"
    display_name: "Python AI MCP Backend"
    branch: "develop"
    artifact_name: "repo3-stats"

# GitHub organization/user settings
github:
  organization: "guillermo-affiliaction"
  base_url: "https://github.com"

# Author pattern matching
author_patterns:
  guillermo:
    - "guillermo.*affiliaction"
    - "Guillermo.*Affiliaction"
  bots:
    - ".*\\[bot\\]$"
    - "gpt-engineer-app.*"

# Processing settings
processing:
  timeout_seconds: 120
  git_fame_format: "json"

# Report settings
report:
  title: "📊 Unified Code Statistics"
  sections:
    - "Global Summary"
    - "Contributions by Repository and Author"
  date_format: "%B %d, %Y at %H:%M UTC"

# Artifact settings
artifacts:
  retention_days: 1
  stats_filename: "repo_stats.json"
  report_filename: "STATS.md"

# Analytics and historical tracking
analytics:
  track_history: true
  retention_days: 90
  trend_analysis: true
  goal_tracking: true

  # Growth tracking settings
  growth_tracking:
    enabled: true
    metrics:
      - "total_loc"
      - "total_commits"
      - "total_files"
      - "guillermo_loc"
      - "guillermo_commits"
      - "guillermo_files"

  # Velocity metrics (weekly/monthly rates)
  velocity_metrics:
    enabled: true
    periods:
      - "weekly"
      - "monthly"
      - "quarterly"

  # Goal tracking
  goals:
    enabled: true
    targets:
      total_loc: 150000
      total_commits: 500
      guillermo_loc: 100000
      guillermo_commits: 300
    milestones:
      - name: "100k LOC"
        target: 100000
        metric: "total_loc"
      - name: "500 Commits"
        target: 500
        metric: "total_commits"
      - name: "50k Guillermo LOC"
        target: 50000
        metric: "guillermo_loc"
